version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    image: itri/rag_demo:20240602
    env_file:
      - .env
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./app:/app
    ports:
      - "${HOST_PORT}:7860"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility